name: mandatory tests
on: [push]
jobs:
  test-functions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: minunit
    steps:
    - uses: actions/checkout@v2
    - name: Install Git
      uses: actions/setup-git@v2
      with:
        git-version: 2.37
    - name: mandatory Tests
      run: make t