name: mandatory part
on: [push]
jobs:
  mandatory-part:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: minunit
    steps:
    - uses: actions/checkout@v2
    - name: compile
      run: compile
    - name: mandatory test
      run: make m